### ISSUE TITLE
Logging and Event Subscription

### ISSUE THREAD

**Issue by cchandel** [gravestench/akara#7]
Hi,
   Thank you for the code. I've been experimenting with this for a simulator.

   How would you recommend I log events and updates?
   
   Is there a method to implement the observer pattern where systems can subscribe to events? Does your eventemitter repo address this?

**Comment by gravestench** [comment]
Yes, the event emitter would address this. You could share a single `EventEmitter` between all systems as a global event emitter.

**Comment by gravestench** [comment]
Also, I know that my examples/readme need to be updated. Looking through it now, I can spot some things that need fixing, but I'm about to head of for the night. For some more fleshed out examples of `akara` in use, please see [director](https://github.com/gravestench/director).

**Comment by gravestench** [comment]
I honestly think that introducing an event bus can make your code really hard to manage. It's one of the reasons I took it out of akara (it used to be here!).

For some inspiration, you can look at what I did with [director's file loader system](https://github.com/gravestench/director/blob/main/pkg/systems/file_loader/sys_loader.go), which uses subscriptions to entities that have `Request` and `Response` components. These subscriptions are used for filtering which file entities need to be loaded, and which have already been processed.

To be fair, though, this code would likely be much simpler to interpret if I had used an event bus. I've been toying with the idea of adding such an event bus to `director` for some time, so am open to suggestions!
